// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBclcEXX7_R1gHRtWZ6vexXsyLZx6VZxtw',
    appId: '1:739924250673:web:620e587f4fbf8070350510',
    messagingSenderId: '739924250673',
    projectId: 'shed-solution',
    authDomain: 'shed-solution.firebaseapp.com',
    storageBucket: 'shed-solution.appspot.com',
    measurementId: 'G-MLZ368V1EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI_F6dB-MQENeYaQjGbopKz6jSxpAicvM',
    appId: '1:739924250673:android:d193eeb95e74c9b8350510',
    messagingSenderId: '739924250673',
    projectId: 'shed-solution',
    storageBucket: 'shed-solution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAon9MmEhw9WmKoekV-NSmoVwBWX1tql4w',
    appId: '1:739924250673:ios:6d0ac5ebae1d8898350510',
    messagingSenderId: '739924250673',
    projectId: 'shed-solution',
    storageBucket: 'shed-solution.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAon9MmEhw9WmKoekV-NSmoVwBWX1tql4w',
    appId: '1:739924250673:ios:6d0ac5ebae1d8898350510',
    messagingSenderId: '739924250673',
    projectId: 'shed-solution',
    storageBucket: 'shed-solution.appspot.com',
    iosBundleId: 'com.example.project',
  );
}
