// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUjja2XAq64_DCSWlDYSgcyWR640dlFxo',
    appId: '1:1028934429651:web:aeae8116c241f34c205d26',
    messagingSenderId: '1028934429651',
    projectId: 'shed-solution-68012',
    authDomain: 'shed-solution-68012.firebaseapp.com',
    storageBucket: 'shed-solution-68012.appspot.com',
    measurementId: 'G-EM36H5T7NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC12afVcMYtN2ZusO5tk8adj316_WaBqB0',
    appId: '1:1028934429651:android:656d47d471f050d3205d26',
    messagingSenderId: '1028934429651',
    projectId: 'shed-solution-68012',
    storageBucket: 'shed-solution-68012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5BurATpRh3KxKr7_j7nYI8K_-N27pwY',
    appId: '1:1028934429651:ios:16974df3798e6916205d26',
    messagingSenderId: '1028934429651',
    projectId: 'shed-solution-68012',
    storageBucket: 'shed-solution-68012.appspot.com',
    iosClientId: '1028934429651-lsb6i7imcom4ebng94l9u5cjpl60c5nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt5BurATpRh3KxKr7_j7nYI8K_-N27pwY',
    appId: '1:1028934429651:ios:16974df3798e6916205d26',
    messagingSenderId: '1028934429651',
    projectId: 'shed-solution-68012',
    storageBucket: 'shed-solution-68012.appspot.com',
    iosClientId: '1028934429651-lsb6i7imcom4ebng94l9u5cjpl60c5nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
